name: cpc_platform
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.4
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  get: ^4.3.4
  google_fonts: ^2.1.0
  hovering: ^1.0.4
  liquid_progress_indicator: ^0.4.0
  lottie: ^1.1.0
  firebase_storage: 10.0.2
  flutter: 
    sdk: flutter
  firebase_storage_web: ^3.0.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

